version: "3.5"
services:
    dexter:
        #image: gcr.io/whiteblock/binance/dexter
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "50052:50052"
        environment:
            PG_URL: "postgres://dexter:b1nanc3@pg:5432/dexter?sslmode=disable"
            DEXTER_DATA_ENDPOINT: "dexter-data:50051"
        depends_on: [ "pg", "dexter-data" ]
    dexter-data:
        #image: gcr.io/whiteblock/binance/dexter-data
        build:
            context: dexter-data
            dockerfile: Dockerfile
        ports:
        - "50051:50051"
    grpcwebproxy-dexter:
        build:
            context: .
            dockerfile: Dockerfile-grpcwebproxy
        command: [ "/usr/local/bin/grpcwebproxy", "--backend_addr", "dexter:50052", "--backend_tls_noverify", "--run_http_server", "--allow_all_origins", "--run_tls_server=false", "--server_http_max_read_timeout=1h", "--server_http_max_write_timeout=1h", "--use_websockets" ]
        ports:
        - "8082:8080"
    grpcwebproxy-dexter-data:
        build:
            context: .
            dockerfile: Dockerfile-grpcwebproxy
        command: [ "/usr/local/bin/grpcwebproxy", "--backend_addr", "dexter-data:50051", "--backend_tls_noverify", "--run_http_server", "--allow_all_origins", "--run_tls_server=false", "--server_http_max_read_timeout=1h", "--server_http_max_write_timeout=1h", "--use_websockets" ]
        ports:
        - "8081:8080"
    pg:
        image: postgres:11.4-alpine
        ports:
        - "5432:5432"
        volumes:
            - './pgdata:/var/lib/postgresql'
            - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached'
        environment:
            POSTGRES_PASSWORD: "b1nanc3"
            POSTGRES_USER: "dexter"
            POSTGRES_DB: "dexter"

