// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alerts.proto

package alerts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Condition int32

const (
	Condition_Crossing          Condition = 0
	Condition_CrossingUp        Condition = 1
	Condition_CrossingDown      Condition = 2
	Condition_GreaterThan       Condition = 3
	Condition_LessThan          Condition = 4
	Condition_EnteringChannel   Condition = 5
	Condition_ExitingChannel    Condition = 6
	Condition_InsideChannel     Condition = 7
	Condition_OutsideChannel    Condition = 8
	Condition_MovingUp          Condition = 9
	Condition_MovingDown        Condition = 10
	Condition_MovingUpPercent   Condition = 11
	Condition_MovingDownPercent Condition = 12
)

var Condition_name = map[int32]string{
	0:  "Crossing",
	1:  "CrossingUp",
	2:  "CrossingDown",
	3:  "GreaterThan",
	4:  "LessThan",
	5:  "EnteringChannel",
	6:  "ExitingChannel",
	7:  "InsideChannel",
	8:  "OutsideChannel",
	9:  "MovingUp",
	10: "MovingDown",
	11: "MovingUpPercent",
	12: "MovingDownPercent",
}

var Condition_value = map[string]int32{
	"Crossing":          0,
	"CrossingUp":        1,
	"CrossingDown":      2,
	"GreaterThan":       3,
	"LessThan":          4,
	"EnteringChannel":   5,
	"ExitingChannel":    6,
	"InsideChannel":     7,
	"OutsideChannel":    8,
	"MovingUp":          9,
	"MovingDown":        10,
	"MovingUpPercent":   11,
	"MovingDownPercent": 12,
}

func (x Condition) String() string {
	return proto.EnumName(Condition_name, int32(x))
}

func (Condition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{0}
}

type Frequency int32

const (
	Frequency_OnlyOnce        Frequency = 0
	Frequency_OncePerBar      Frequency = 1
	Frequency_OncePerBarClose Frequency = 2
	Frequency_OncePerMinute   Frequency = 3
)

var Frequency_name = map[int32]string{
	0: "OnlyOnce",
	1: "OncePerBar",
	2: "OncePerBarClose",
	3: "OncePerMinute",
}

var Frequency_value = map[string]int32{
	"OnlyOnce":        0,
	"OncePerBar":      1,
	"OncePerBarClose": 2,
	"OncePerMinute":   3,
}

func (x Frequency) String() string {
	return proto.EnumName(Frequency_name, int32(x))
}

func (Frequency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{1}
}

type Chart struct {
	ChartId              uint64   `protobuf:"varint,1,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
	ExternalId           string   `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market               string   `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chart) Reset()         { *m = Chart{} }
func (m *Chart) String() string { return proto.CompactTextString(m) }
func (*Chart) ProtoMessage()    {}
func (*Chart) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{0}
}

func (m *Chart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chart.Unmarshal(m, b)
}
func (m *Chart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chart.Marshal(b, m, deterministic)
}
func (m *Chart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chart.Merge(m, src)
}
func (m *Chart) XXX_Size() int {
	return xxx_messageInfo_Chart.Size(m)
}
func (m *Chart) XXX_DiscardUnknown() {
	xxx_messageInfo_Chart.DiscardUnknown(m)
}

var xxx_messageInfo_Chart proto.InternalMessageInfo

func (m *Chart) GetChartId() uint64 {
	if m != nil {
		return m.ChartId
	}
	return 0
}

func (m *Chart) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Chart) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Chart) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type Webhook struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Webhook) Reset()         { *m = Webhook{} }
func (m *Webhook) String() string { return proto.CompactTextString(m) }
func (*Webhook) ProtoMessage()    {}
func (*Webhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{1}
}

func (m *Webhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Webhook.Unmarshal(m, b)
}
func (m *Webhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Webhook.Marshal(b, m, deterministic)
}
func (m *Webhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Webhook.Merge(m, src)
}
func (m *Webhook) XXX_Size() int {
	return xxx_messageInfo_Webhook.Size(m)
}
func (m *Webhook) XXX_DiscardUnknown() {
	xxx_messageInfo_Webhook.DiscardUnknown(m)
}

var xxx_messageInfo_Webhook proto.InternalMessageInfo

func (m *Webhook) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Webhook) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Webhook) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Alert struct {
	AlertId              uint64    `protobuf:"varint,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	ExternalId           uint64    `protobuf:"varint,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Chart                *Chart    `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	Timeframe            string    `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	LineA                string    `protobuf:"bytes,5,opt,name=line_a,json=lineA,proto3" json:"line_a,omitempty"`
	Condition            Condition `protobuf:"varint,6,opt,name=condition,proto3,enum=alerts.Condition" json:"condition,omitempty"`
	LineB                string    `protobuf:"bytes,7,opt,name=line_b,json=lineB,proto3" json:"line_b,omitempty"`
	Frequency            Frequency `protobuf:"varint,8,opt,name=frequency,proto3,enum=alerts.Frequency" json:"frequency,omitempty"`
	MessageBody          string    `protobuf:"bytes,9,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	Webhook              *Webhook  `protobuf:"bytes,10,opt,name=webhook,proto3" json:"webhook,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{2}
}

func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (m *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(m, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetAlertId() uint64 {
	if m != nil {
		return m.AlertId
	}
	return 0
}

func (m *Alert) GetExternalId() uint64 {
	if m != nil {
		return m.ExternalId
	}
	return 0
}

func (m *Alert) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *Alert) GetTimeframe() string {
	if m != nil {
		return m.Timeframe
	}
	return ""
}

func (m *Alert) GetLineA() string {
	if m != nil {
		return m.LineA
	}
	return ""
}

func (m *Alert) GetCondition() Condition {
	if m != nil {
		return m.Condition
	}
	return Condition_Crossing
}

func (m *Alert) GetLineB() string {
	if m != nil {
		return m.LineB
	}
	return ""
}

func (m *Alert) GetFrequency() Frequency {
	if m != nil {
		return m.Frequency
	}
	return Frequency_OnlyOnce
}

func (m *Alert) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func (m *Alert) GetWebhook() *Webhook {
	if m != nil {
		return m.Webhook
	}
	return nil
}

type Indicator struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Implementation       string   `protobuf:"bytes,2,opt,name=implementation,proto3" json:"implementation,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Inputs               string   `protobuf:"bytes,4,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Lines                string   `protobuf:"bytes,5,opt,name=lines,proto3" json:"lines,omitempty"`
	Styles               string   `protobuf:"bytes,6,opt,name=styles,proto3" json:"styles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Indicator) Reset()         { *m = Indicator{} }
func (m *Indicator) String() string { return proto.CompactTextString(m) }
func (*Indicator) ProtoMessage()    {}
func (*Indicator) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{3}
}

func (m *Indicator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Indicator.Unmarshal(m, b)
}
func (m *Indicator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Indicator.Marshal(b, m, deterministic)
}
func (m *Indicator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Indicator.Merge(m, src)
}
func (m *Indicator) XXX_Size() int {
	return xxx_messageInfo_Indicator.Size(m)
}
func (m *Indicator) XXX_DiscardUnknown() {
	xxx_messageInfo_Indicator.DiscardUnknown(m)
}

var xxx_messageInfo_Indicator proto.InternalMessageInfo

func (m *Indicator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Indicator) GetImplementation() string {
	if m != nil {
		return m.Implementation
	}
	return ""
}

func (m *Indicator) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Indicator) GetInputs() string {
	if m != nil {
		return m.Inputs
	}
	return ""
}

func (m *Indicator) GetLines() string {
	if m != nil {
		return m.Lines
	}
	return ""
}

func (m *Indicator) GetStyles() string {
	if m != nil {
		return m.Styles
	}
	return ""
}

type ListAlertsRequest struct {
	ExternalId           uint64   `protobuf:"varint,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlertsRequest) Reset()         { *m = ListAlertsRequest{} }
func (m *ListAlertsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlertsRequest) ProtoMessage()    {}
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{4}
}

func (m *ListAlertsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertsRequest.Unmarshal(m, b)
}
func (m *ListAlertsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertsRequest.Marshal(b, m, deterministic)
}
func (m *ListAlertsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertsRequest.Merge(m, src)
}
func (m *ListAlertsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlertsRequest.Size(m)
}
func (m *ListAlertsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertsRequest proto.InternalMessageInfo

func (m *ListAlertsRequest) GetExternalId() uint64 {
	if m != nil {
		return m.ExternalId
	}
	return 0
}

type ListAlertsResponse struct {
	Alerts               []*Alert `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlertsResponse) Reset()         { *m = ListAlertsResponse{} }
func (m *ListAlertsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAlertsResponse) ProtoMessage()    {}
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{5}
}

func (m *ListAlertsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertsResponse.Unmarshal(m, b)
}
func (m *ListAlertsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertsResponse.Marshal(b, m, deterministic)
}
func (m *ListAlertsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertsResponse.Merge(m, src)
}
func (m *ListAlertsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAlertsResponse.Size(m)
}
func (m *ListAlertsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertsResponse proto.InternalMessageInfo

func (m *ListAlertsResponse) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type GetAlertRequest struct {
	ExternalId           uint64   `protobuf:"varint,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlertRequest) Reset()         { *m = GetAlertRequest{} }
func (m *GetAlertRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlertRequest) ProtoMessage()    {}
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{6}
}

func (m *GetAlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlertRequest.Unmarshal(m, b)
}
func (m *GetAlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlertRequest.Marshal(b, m, deterministic)
}
func (m *GetAlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlertRequest.Merge(m, src)
}
func (m *GetAlertRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlertRequest.Size(m)
}
func (m *GetAlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlertRequest proto.InternalMessageInfo

func (m *GetAlertRequest) GetExternalId() uint64 {
	if m != nil {
		return m.ExternalId
	}
	return 0
}

type DeleteAlertRequest struct {
	AlertId              uint64   `protobuf:"varint,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlertRequest) Reset()         { *m = DeleteAlertRequest{} }
func (m *DeleteAlertRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAlertRequest) ProtoMessage()    {}
func (*DeleteAlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{7}
}

func (m *DeleteAlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlertRequest.Unmarshal(m, b)
}
func (m *DeleteAlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlertRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlertRequest.Merge(m, src)
}
func (m *DeleteAlertRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAlertRequest.Size(m)
}
func (m *DeleteAlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlertRequest proto.InternalMessageInfo

func (m *DeleteAlertRequest) GetAlertId() uint64 {
	if m != nil {
		return m.AlertId
	}
	return 0
}

type DeleteAlertResponse struct {
	AlertId              uint64   `protobuf:"varint,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlertResponse) Reset()         { *m = DeleteAlertResponse{} }
func (m *DeleteAlertResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAlertResponse) ProtoMessage()    {}
func (*DeleteAlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{8}
}

func (m *DeleteAlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlertResponse.Unmarshal(m, b)
}
func (m *DeleteAlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlertResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlertResponse.Merge(m, src)
}
func (m *DeleteAlertResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAlertResponse.Size(m)
}
func (m *DeleteAlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlertResponse proto.InternalMessageInfo

func (m *DeleteAlertResponse) GetAlertId() uint64 {
	if m != nil {
		return m.AlertId
	}
	return 0
}

type ListIndicatorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIndicatorsRequest) Reset()         { *m = ListIndicatorsRequest{} }
func (m *ListIndicatorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListIndicatorsRequest) ProtoMessage()    {}
func (*ListIndicatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{9}
}

func (m *ListIndicatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIndicatorsRequest.Unmarshal(m, b)
}
func (m *ListIndicatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIndicatorsRequest.Marshal(b, m, deterministic)
}
func (m *ListIndicatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIndicatorsRequest.Merge(m, src)
}
func (m *ListIndicatorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListIndicatorsRequest.Size(m)
}
func (m *ListIndicatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIndicatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIndicatorsRequest proto.InternalMessageInfo

type ListIndicatorsResponse struct {
	Indicators           []*Indicator `protobuf:"bytes,1,rep,name=indicators,proto3" json:"indicators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListIndicatorsResponse) Reset()         { *m = ListIndicatorsResponse{} }
func (m *ListIndicatorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListIndicatorsResponse) ProtoMessage()    {}
func (*ListIndicatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20493709c38b81dc, []int{10}
}

func (m *ListIndicatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIndicatorsResponse.Unmarshal(m, b)
}
func (m *ListIndicatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIndicatorsResponse.Marshal(b, m, deterministic)
}
func (m *ListIndicatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIndicatorsResponse.Merge(m, src)
}
func (m *ListIndicatorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListIndicatorsResponse.Size(m)
}
func (m *ListIndicatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIndicatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIndicatorsResponse proto.InternalMessageInfo

func (m *ListIndicatorsResponse) GetIndicators() []*Indicator {
	if m != nil {
		return m.Indicators
	}
	return nil
}

func init() {
	proto.RegisterEnum("alerts.Condition", Condition_name, Condition_value)
	proto.RegisterEnum("alerts.Frequency", Frequency_name, Frequency_value)
	proto.RegisterType((*Chart)(nil), "alerts.Chart")
	proto.RegisterType((*Webhook)(nil), "alerts.Webhook")
	proto.RegisterType((*Alert)(nil), "alerts.Alert")
	proto.RegisterType((*Indicator)(nil), "alerts.Indicator")
	proto.RegisterType((*ListAlertsRequest)(nil), "alerts.ListAlertsRequest")
	proto.RegisterType((*ListAlertsResponse)(nil), "alerts.ListAlertsResponse")
	proto.RegisterType((*GetAlertRequest)(nil), "alerts.GetAlertRequest")
	proto.RegisterType((*DeleteAlertRequest)(nil), "alerts.DeleteAlertRequest")
	proto.RegisterType((*DeleteAlertResponse)(nil), "alerts.DeleteAlertResponse")
	proto.RegisterType((*ListIndicatorsRequest)(nil), "alerts.ListIndicatorsRequest")
	proto.RegisterType((*ListIndicatorsResponse)(nil), "alerts.ListIndicatorsResponse")
}

func init() { proto.RegisterFile("alerts.proto", fileDescriptor_20493709c38b81dc) }

var fileDescriptor_20493709c38b81dc = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0xad, 0x2b, 0x87, 0x8a, 0x4c, 0x4f, 0xea, 0x84, 0x51, 0x6f, 0x2a, 0x8b, 0x16, 0x6e,
	0x80, 0x24, 0xad, 0x9a, 0xb7, 0x3e, 0xc5, 0x8a, 0xeb, 0x0a, 0x4d, 0xe0, 0x84, 0x68, 0xd0, 0x47,
	0x83, 0x22, 0x27, 0x12, 0x11, 0x6a, 0x57, 0xdd, 0x5d, 0xd5, 0xd6, 0x5b, 0x7f, 0xa6, 0x7f, 0xd6,
	0x4f, 0xe8, 0x07, 0x14, 0xbb, 0xe4, 0x52, 0x94, 0xe4, 0x14, 0x7e, 0xe3, 0x99, 0x99, 0x3d, 0x3b,
	0x67, 0xe6, 0xac, 0x04, 0xbd, 0x38, 0x27, 0xa1, 0xe4, 0xd3, 0xa5, 0xe0, 0x8a, 0x63, 0xbb, 0x40,
	0xe1, 0x35, 0xb4, 0xc6, 0xf3, 0x58, 0x28, 0x7c, 0x04, 0xdd, 0x44, 0x7f, 0x5c, 0x65, 0x69, 0xe0,
	0x0c, 0x9d, 0xd3, 0x66, 0xd4, 0x31, 0x78, 0x92, 0xe2, 0x97, 0xe0, 0xd1, 0x8d, 0x22, 0xc1, 0xe2,
	0x5c, 0x67, 0x0f, 0x87, 0xce, 0xa9, 0x1b, 0x81, 0x0d, 0x4d, 0x52, 0x1c, 0x40, 0x97, 0x6e, 0x92,
	0x79, 0xcc, 0x66, 0x14, 0x34, 0x4c, 0xb6, 0xc2, 0xf8, 0x00, 0xda, 0x8b, 0x58, 0x7c, 0x20, 0x15,
	0x34, 0x4d, 0xa6, 0x44, 0xe1, 0x05, 0x74, 0x7e, 0xa7, 0xe9, 0x9c, 0xf3, 0x0f, 0xa6, 0x84, 0xd4,
	0x9c, 0x17, 0x17, 0xeb, 0x12, 0x83, 0xd0, 0x87, 0xc6, 0x4a, 0xe4, 0xe5, 0x7d, 0xfa, 0x13, 0x11,
	0x9a, 0x53, 0x9e, 0xae, 0xcb, 0x4b, 0xcc, 0x77, 0xf8, 0xcf, 0x21, 0xb4, 0x5e, 0x68, 0x31, 0x5a,
	0x82, 0x51, 0x55, 0x93, 0x60, 0xf0, 0xed, 0x12, 0x9a, 0x5b, 0x12, 0xbe, 0x86, 0x96, 0x91, 0x6b,
	0xa8, 0xbd, 0xd1, 0xbd, 0xa7, 0xe5, 0xb4, 0xcc, 0x70, 0xa2, 0x22, 0x87, 0x9f, 0x81, 0xab, 0xb2,
	0x05, 0xbd, 0x17, 0xf1, 0x82, 0x4a, 0x39, 0x9b, 0x00, 0x9e, 0x40, 0x3b, 0xcf, 0x18, 0x5d, 0xc5,
	0x41, 0xcb, 0xa4, 0x5a, 0x1a, 0xbd, 0xc0, 0x67, 0xe0, 0x26, 0x9c, 0xa5, 0x99, 0xca, 0x38, 0x0b,
	0xda, 0x43, 0xe7, 0xb4, 0x3f, 0x3a, 0xae, 0xd8, 0x6d, 0x22, 0xda, 0xd4, 0x54, 0x3c, 0xd3, 0xa0,
	0xb3, 0xe1, 0x39, 0xd3, 0x3c, 0xef, 0x05, 0xfd, 0xb1, 0x22, 0x96, 0xac, 0x83, 0xee, 0x36, 0xcf,
	0xcf, 0x36, 0x11, 0x6d, 0x6a, 0xf0, 0x2b, 0xe8, 0x2d, 0x48, 0xca, 0x78, 0x46, 0x57, 0x66, 0x68,
	0xae, 0x61, 0xf3, 0xca, 0xd8, 0x19, 0x4f, 0xd7, 0xf8, 0x1d, 0x74, 0xae, 0x8b, 0x25, 0x04, 0x60,
	0x74, 0x1f, 0x59, 0xc6, 0x72, 0x37, 0x91, 0xcd, 0x87, 0x7f, 0x3b, 0xe0, 0x4e, 0x58, 0x9a, 0x25,
	0xb1, 0xe2, 0x42, 0x2f, 0x82, 0xe9, 0x21, 0x14, 0x0b, 0x33, 0xdf, 0xf8, 0x2d, 0xf4, 0xb3, 0xc5,
	0x32, 0xa7, 0x05, 0x31, 0x15, 0x1b, 0xb5, 0xc5, 0xe6, 0x76, 0xa2, 0x7a, 0xdd, 0x92, 0xaf, 0x44,
	0x62, 0xbd, 0x52, 0x22, 0x1d, 0xcf, 0xd8, 0x72, 0xa5, 0xa4, 0x75, 0x4a, 0x81, 0xf0, 0x13, 0x30,
	0x13, 0x90, 0xf5, 0xb1, 0x4a, 0xc3, 0xa2, 0xd6, 0x39, 0x49, 0x33, 0x53, 0xcd, 0x62, 0x50, 0xf8,
	0x1c, 0x8e, 0x5f, 0x65, 0x52, 0x19, 0x47, 0xc8, 0x48, 0xcf, 0x42, 0xaa, 0xdd, 0xf5, 0x3b, 0xbb,
	0xeb, 0x0f, 0x7f, 0x02, 0xac, 0x9f, 0x92, 0x4b, 0xce, 0x24, 0xe1, 0x37, 0x50, 0x3e, 0x93, 0xc0,
	0x19, 0x36, 0xea, 0xae, 0x30, 0x75, 0x91, 0x7d, 0x43, 0x23, 0x38, 0xba, 0xa0, 0xe2, 0xec, 0x9d,
	0x2f, 0x7c, 0x06, 0xf8, 0x92, 0x72, 0x52, 0xb4, 0x75, 0xec, 0xe3, 0x0e, 0x0e, 0xbf, 0x87, 0xfb,
	0x5b, 0x07, 0xca, 0x16, 0xff, 0xe7, 0xc4, 0x43, 0x38, 0xd1, 0x9a, 0xaa, 0xa5, 0xd9, 0x69, 0x84,
	0xbf, 0xc2, 0x83, 0xdd, 0x44, 0xc9, 0xf6, 0x03, 0x40, 0x56, 0x45, 0x4b, 0xd1, 0x95, 0xc9, 0xaa,
	0xfa, 0xa8, 0x56, 0xf4, 0xf8, 0x5f, 0x07, 0xdc, 0xca, 0xc6, 0xd8, 0x83, 0xee, 0x58, 0x70, 0x29,
	0x33, 0x36, 0xf3, 0x0f, 0xb0, 0x0f, 0x60, 0xd1, 0xbb, 0xa5, 0xef, 0xa0, 0x0f, 0x3d, 0x8b, 0x5f,
	0xf2, 0x6b, 0xe6, 0x1f, 0xe2, 0x11, 0x78, 0x17, 0x82, 0x62, 0x45, 0xe2, 0xb7, 0x79, 0xcc, 0xfc,
	0x86, 0x26, 0x78, 0x45, 0x52, 0x1a, 0xd4, 0xc4, 0xfb, 0x70, 0x74, 0xce, 0x14, 0x89, 0x8c, 0xcd,
	0xc6, 0xf3, 0x98, 0x31, 0xca, 0xfd, 0x16, 0x22, 0xf4, 0xcf, 0x6f, 0x32, 0x55, 0x8b, 0xb5, 0xf1,
	0x18, 0xee, 0x4d, 0x98, 0xcc, 0x52, 0xb2, 0xa1, 0x8e, 0x2e, 0xbb, 0x5c, 0xa9, 0x7a, 0xac, 0xab,
	0xd9, 0x5f, 0xf3, 0x3f, 0x8b, 0x76, 0x5c, 0xdd, 0x5e, 0x81, 0x4c, 0x33, 0xa0, 0x6f, 0xb3, 0xd9,
	0x37, 0x24, 0x12, 0x62, 0xca, 0xf7, 0xf0, 0x04, 0x8e, 0x37, 0x45, 0x36, 0xdc, 0x7b, 0xfc, 0x16,
	0xdc, 0xea, 0xd1, 0x69, 0xda, 0x4b, 0x96, 0xaf, 0x2f, 0x59, 0x42, 0x85, 0x6a, 0xfd, 0xf5, 0x86,
	0xc4, 0x59, 0x2c, 0x7c, 0x47, 0xd3, 0x6e, 0xf0, 0x38, 0xe7, 0x92, 0xfc, 0x43, 0xdd, 0x70, 0x19,
	0x7c, 0x9d, 0xb1, 0x95, 0x22, 0xbf, 0x31, 0xfa, 0xab, 0x01, 0xed, 0xc2, 0x80, 0xf8, 0x04, 0xbc,
	0xb1, 0x19, 0x4b, 0xf1, 0xc3, 0xb6, 0xed, 0xbb, 0xc1, 0x36, 0x0c, 0x0f, 0xf0, 0x1c, 0x60, 0xe3,
	0x5e, 0x7c, 0x64, 0xd3, 0x7b, 0xef, 0x60, 0x30, 0xb8, 0x2d, 0x55, 0xec, 0x3e, 0x3c, 0xc0, 0xe7,
	0xd0, 0xb5, 0x3e, 0xc6, 0x87, 0xb6, 0x72, 0xc7, 0xd9, 0xfb, 0x97, 0x3f, 0x01, 0xef, 0xdd, 0x32,
	0xbd, 0x73, 0xaf, 0xbf, 0x80, 0x57, 0xf3, 0x31, 0x56, 0x1d, 0xed, 0xbf, 0x86, 0xc1, 0xa7, 0xb7,
	0xe6, 0xaa, 0x76, 0xdf, 0x42, 0x7f, 0xdb, 0xc6, 0xf8, 0x79, 0x5d, 0xde, 0x9e, 0xef, 0x07, 0x5f,
	0x7c, 0x2c, 0x6d, 0x29, 0xa7, 0x6d, 0xf3, 0xe7, 0xf8, 0xe3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xef, 0x11, 0x8b, 0x72, 0x2c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlertsClient is the client API for Alerts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlertsClient interface {
	CreateAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Alert, error)
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	UpdateAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Alert, error)
	DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error)
	ListIndicators(ctx context.Context, in *ListIndicatorsRequest, opts ...grpc.CallOption) (*ListIndicatorsResponse, error)
}

type alertsClient struct {
	cc *grpc.ClientConn
}

func NewAlertsClient(cc *grpc.ClientConn) AlertsClient {
	return &alertsClient{cc}
}

func (c *alertsClient) CreateAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Alert, error) {
	out := new(Alert)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/CreateAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/ListAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	out := new(Alert)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/GetAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) UpdateAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Alert, error) {
	out := new(Alert)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/UpdateAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error) {
	out := new(DeleteAlertResponse)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/DeleteAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) ListIndicators(ctx context.Context, in *ListIndicatorsRequest, opts ...grpc.CallOption) (*ListIndicatorsResponse, error) {
	out := new(ListIndicatorsResponse)
	err := c.cc.Invoke(ctx, "/alerts.Alerts/ListIndicators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertsServer is the server API for Alerts service.
type AlertsServer interface {
	CreateAlert(context.Context, *Alert) (*Alert, error)
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	UpdateAlert(context.Context, *Alert) (*Alert, error)
	DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error)
	ListIndicators(context.Context, *ListIndicatorsRequest) (*ListIndicatorsResponse, error)
}

func RegisterAlertsServer(s *grpc.Server, srv AlertsServer) {
	s.RegisterService(&_Alerts_serviceDesc, srv)
}

func _Alerts_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/CreateAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).CreateAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/ListAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/GetAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_UpdateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).UpdateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/UpdateAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).UpdateAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_DeleteAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).DeleteAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/DeleteAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).DeleteAlert(ctx, req.(*DeleteAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_ListIndicators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndicatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).ListIndicators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerts.Alerts/ListIndicators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).ListIndicators(ctx, req.(*ListIndicatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alerts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alerts.Alerts",
	HandlerType: (*AlertsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlert",
			Handler:    _Alerts_CreateAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _Alerts_ListAlerts_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _Alerts_GetAlert_Handler,
		},
		{
			MethodName: "UpdateAlert",
			Handler:    _Alerts_UpdateAlert_Handler,
		},
		{
			MethodName: "DeleteAlert",
			Handler:    _Alerts_DeleteAlert_Handler,
		},
		{
			MethodName: "ListIndicators",
			Handler:    _Alerts_ListIndicators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alerts.proto",
}
