// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExchangesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangesRequest) Reset()         { *m = ExchangesRequest{} }
func (m *ExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangesRequest) ProtoMessage()    {}
func (*ExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *ExchangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangesRequest.Unmarshal(m, b)
}
func (m *ExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangesRequest.Marshal(b, m, deterministic)
}
func (m *ExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangesRequest.Merge(m, src)
}
func (m *ExchangesRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangesRequest.Size(m)
}
func (m *ExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangesRequest proto.InternalMessageInfo

type ExchangesResponse struct {
	Exchanges            []string `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangesResponse) Reset()         { *m = ExchangesResponse{} }
func (m *ExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangesResponse) ProtoMessage()    {}
func (*ExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ExchangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangesResponse.Unmarshal(m, b)
}
func (m *ExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangesResponse.Marshal(b, m, deterministic)
}
func (m *ExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangesResponse.Merge(m, src)
}
func (m *ExchangesResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangesResponse.Size(m)
}
func (m *ExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangesResponse proto.InternalMessageInfo

func (m *ExchangesResponse) GetExchanges() []string {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type MarketsRequest struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketsRequest) Reset()         { *m = MarketsRequest{} }
func (m *MarketsRequest) String() string { return proto.CompactTextString(m) }
func (*MarketsRequest) ProtoMessage()    {}
func (*MarketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *MarketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketsRequest.Unmarshal(m, b)
}
func (m *MarketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketsRequest.Marshal(b, m, deterministic)
}
func (m *MarketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketsRequest.Merge(m, src)
}
func (m *MarketsRequest) XXX_Size() int {
	return xxx_messageInfo_MarketsRequest.Size(m)
}
func (m *MarketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketsRequest proto.InternalMessageInfo

func (m *MarketsRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type MarketsResponse struct {
	Markets              []string `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketsResponse) Reset()         { *m = MarketsResponse{} }
func (m *MarketsResponse) String() string { return proto.CompactTextString(m) }
func (*MarketsResponse) ProtoMessage()    {}
func (*MarketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *MarketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketsResponse.Unmarshal(m, b)
}
func (m *MarketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketsResponse.Marshal(b, m, deterministic)
}
func (m *MarketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketsResponse.Merge(m, src)
}
func (m *MarketsResponse) XXX_Size() int {
	return xxx_messageInfo_MarketsResponse.Size(m)
}
func (m *MarketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarketsResponse proto.InternalMessageInfo

func (m *MarketsResponse) GetMarkets() []string {
	if m != nil {
		return m.Markets
	}
	return nil
}

type CandlesRequest struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Timeframe            string   `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandlesRequest) Reset()         { *m = CandlesRequest{} }
func (m *CandlesRequest) String() string { return proto.CompactTextString(m) }
func (*CandlesRequest) ProtoMessage()    {}
func (*CandlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *CandlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandlesRequest.Unmarshal(m, b)
}
func (m *CandlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandlesRequest.Marshal(b, m, deterministic)
}
func (m *CandlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandlesRequest.Merge(m, src)
}
func (m *CandlesRequest) XXX_Size() int {
	return xxx_messageInfo_CandlesRequest.Size(m)
}
func (m *CandlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CandlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CandlesRequest proto.InternalMessageInfo

func (m *CandlesRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *CandlesRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *CandlesRequest) GetTimeframe() string {
	if m != nil {
		return m.Timeframe
	}
	return ""
}

type CandlesResponse struct {
	Candles              []*Candle `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CandlesResponse) Reset()         { *m = CandlesResponse{} }
func (m *CandlesResponse) String() string { return proto.CompactTextString(m) }
func (*CandlesResponse) ProtoMessage()    {}
func (*CandlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *CandlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandlesResponse.Unmarshal(m, b)
}
func (m *CandlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandlesResponse.Marshal(b, m, deterministic)
}
func (m *CandlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandlesResponse.Merge(m, src)
}
func (m *CandlesResponse) XXX_Size() int {
	return xxx_messageInfo_CandlesResponse.Size(m)
}
func (m *CandlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandlesResponse proto.InternalMessageInfo

func (m *CandlesResponse) GetCandles() []*Candle {
	if m != nil {
		return m.Candles
	}
	return nil
}

type Candle struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	O                    float64  `protobuf:"fixed64,2,opt,name=o,proto3" json:"o,omitempty"`
	H                    float64  `protobuf:"fixed64,3,opt,name=h,proto3" json:"h,omitempty"`
	L                    float64  `protobuf:"fixed64,4,opt,name=l,proto3" json:"l,omitempty"`
	C                    float64  `protobuf:"fixed64,5,opt,name=c,proto3" json:"c,omitempty"`
	V                    float64  `protobuf:"fixed64,6,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candle) Reset()         { *m = Candle{} }
func (m *Candle) String() string { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()    {}
func (*Candle) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *Candle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candle.Unmarshal(m, b)
}
func (m *Candle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candle.Marshal(b, m, deterministic)
}
func (m *Candle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candle.Merge(m, src)
}
func (m *Candle) XXX_Size() int {
	return xxx_messageInfo_Candle.Size(m)
}
func (m *Candle) XXX_DiscardUnknown() {
	xxx_messageInfo_Candle.DiscardUnknown(m)
}

var xxx_messageInfo_Candle proto.InternalMessageInfo

func (m *Candle) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Candle) GetO() float64 {
	if m != nil {
		return m.O
	}
	return 0
}

func (m *Candle) GetH() float64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *Candle) GetL() float64 {
	if m != nil {
		return m.L
	}
	return 0
}

func (m *Candle) GetC() float64 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *Candle) GetV() float64 {
	if m != nil {
		return m.V
	}
	return 0
}

type TestRequest struct {
	A                    string   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

type TestResponse struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *TestResponse) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*ExchangesRequest)(nil), "ExchangesRequest")
	proto.RegisterType((*ExchangesResponse)(nil), "ExchangesResponse")
	proto.RegisterType((*MarketsRequest)(nil), "MarketsRequest")
	proto.RegisterType((*MarketsResponse)(nil), "MarketsResponse")
	proto.RegisterType((*CandlesRequest)(nil), "CandlesRequest")
	proto.RegisterType((*CandlesResponse)(nil), "CandlesResponse")
	proto.RegisterType((*Candle)(nil), "Candle")
	proto.RegisterType((*TestRequest)(nil), "TestRequest")
	proto.RegisterType((*TestResponse)(nil), "TestResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcb, 0x8e, 0xda, 0x30,
	0x14, 0x86, 0x63, 0x42, 0x43, 0x39, 0x5c, 0x12, 0xbc, 0xa8, 0xac, 0xb4, 0x0b, 0x6a, 0xa9, 0x12,
	0xea, 0xc5, 0x2a, 0xb4, 0x52, 0x57, 0x5d, 0x95, 0xaa, 0xab, 0x6e, 0x0c, 0x2f, 0xe0, 0x04, 0xcf,
	0x30, 0x9a, 0x84, 0x64, 0x12, 0x83, 0x78, 0x89, 0x79, 0xe7, 0x51, 0x7c, 0x09, 0x97, 0xd1, 0x48,
	0xb3, 0xfc, 0xfe, 0xe3, 0x73, 0xf8, 0x39, 0xff, 0x09, 0xc0, 0x46, 0x28, 0xc1, 0xca, 0xaa, 0x50,
	0x05, 0xc5, 0x10, 0xfd, 0x3d, 0xa6, 0x5b, 0xb1, 0xbb, 0x95, 0x35, 0x97, 0x0f, 0x7b, 0x59, 0x2b,
	0x3a, 0x87, 0xc9, 0x99, 0x56, 0x97, 0xc5, 0xae, 0x96, 0xf8, 0x03, 0xf4, 0xa5, 0x13, 0x09, 0x9a,
	0xfa, 0xb3, 0x3e, 0x3f, 0x09, 0xf4, 0x2b, 0x8c, 0xff, 0x8b, 0xea, 0x5e, 0x2a, 0x37, 0x04, 0xc7,
	0xf0, 0xd6, 0x95, 0x09, 0x9a, 0xa2, 0x59, 0x9f, 0xb7, 0x4c, 0xbf, 0x40, 0xd8, 0xbe, 0xb6, 0xe3,
	0x09, 0xf4, 0x72, 0x23, 0xd9, 0xe1, 0x0e, 0x69, 0x02, 0xe3, 0x3f, 0x62, 0xb7, 0xc9, 0xe4, 0x6b,
	0x46, 0xe3, 0x77, 0x10, 0x98, 0x46, 0xd2, 0xd1, 0x15, 0x4b, 0x8d, 0x7d, 0x75, 0x97, 0xcb, 0x9b,
	0x4a, 0xe4, 0x92, 0xf8, 0xba, 0x74, 0x12, 0xe8, 0x4f, 0x08, 0xdb, 0xdf, 0xb0, 0x86, 0x3e, 0x42,
	0x2f, 0x35, 0x92, 0x36, 0x34, 0x58, 0xf4, 0x98, 0x79, 0xc2, 0x9d, 0x4e, 0x33, 0x08, 0x8c, 0xe4,
	0xa6, 0xd7, 0x4a, 0xe4, 0xa5, 0xb6, 0xd4, 0xe5, 0x27, 0x01, 0x0f, 0x01, 0x15, 0xda, 0x0e, 0xe2,
	0xa8, 0x68, 0x68, 0xab, 0x1d, 0x20, 0x8e, 0xb6, 0x0d, 0x65, 0xa4, 0x6b, 0x28, 0x6b, 0x28, 0x25,
	0x6f, 0x0c, 0xa5, 0x0d, 0x1d, 0x48, 0x60, 0xe8, 0x40, 0xdf, 0xc3, 0x60, 0x2d, 0x6b, 0xe5, 0x96,
	0x30, 0x04, 0x24, 0xec, 0xbf, 0x47, 0x82, 0x7e, 0x86, 0xa1, 0x29, 0x5a, 0xf7, 0x6d, 0xd5, 0xe7,
	0x48, 0x34, 0x94, 0x68, 0x03, 0x3e, 0x47, 0xc9, 0xe2, 0xb1, 0x03, 0xb0, 0x94, 0x47, 0x25, 0xab,
	0xa5, 0x50, 0x02, 0xff, 0x06, 0xbc, 0xda, 0x97, 0x65, 0x51, 0x29, 0xb9, 0x69, 0x63, 0xc7, 0x13,
	0x76, 0x7d, 0x16, 0x31, 0x66, 0xcf, 0xae, 0x82, 0x7a, 0xf8, 0x17, 0x44, 0x6d, 0xbb, 0x0d, 0x15,
	0x87, 0xec, 0xf2, 0x18, 0xe2, 0x88, 0x5d, 0xe5, 0x4d, 0x3d, 0x3c, 0x07, 0xf8, 0x27, 0x95, 0x5d,
	0x3b, 0x0e, 0xd9, 0x65, 0xc8, 0x71, 0xc4, 0xae, 0x12, 0xa1, 0x1e, 0xfe, 0x06, 0xa3, 0x95, 0xaa,
	0xa4, 0xc8, 0x5f, 0xec, 0x72, 0x21, 0x51, 0xef, 0x3b, 0xc2, 0x9f, 0xa0, 0xbb, 0xd6, 0xab, 0x62,
	0x67, 0x8b, 0x8b, 0x47, 0xec, 0x7c, 0x53, 0xd4, 0x4b, 0x02, 0xfd, 0x25, 0xfc, 0x78, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0x5f, 0xc6, 0x8d, 0x17, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DexterDataClient is the client API for DexterData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DexterDataClient interface {
	SupportedExchanges(ctx context.Context, in *ExchangesRequest, opts ...grpc.CallOption) (*ExchangesResponse, error)
	SupportedMarkets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error)
	GetCandles(ctx context.Context, in *CandlesRequest, opts ...grpc.CallOption) (*CandlesResponse, error)
	StreamCandles(ctx context.Context, in *CandlesRequest, opts ...grpc.CallOption) (DexterData_StreamCandlesClient, error)
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type dexterDataClient struct {
	cc *grpc.ClientConn
}

func NewDexterDataClient(cc *grpc.ClientConn) DexterDataClient {
	return &dexterDataClient{cc}
}

func (c *dexterDataClient) SupportedExchanges(ctx context.Context, in *ExchangesRequest, opts ...grpc.CallOption) (*ExchangesResponse, error) {
	out := new(ExchangesResponse)
	err := c.cc.Invoke(ctx, "/DexterData/SupportedExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexterDataClient) SupportedMarkets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error) {
	out := new(MarketsResponse)
	err := c.cc.Invoke(ctx, "/DexterData/SupportedMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexterDataClient) GetCandles(ctx context.Context, in *CandlesRequest, opts ...grpc.CallOption) (*CandlesResponse, error) {
	out := new(CandlesResponse)
	err := c.cc.Invoke(ctx, "/DexterData/GetCandles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexterDataClient) StreamCandles(ctx context.Context, in *CandlesRequest, opts ...grpc.CallOption) (DexterData_StreamCandlesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DexterData_serviceDesc.Streams[0], "/DexterData/StreamCandles", opts...)
	if err != nil {
		return nil, err
	}
	x := &dexterDataStreamCandlesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DexterData_StreamCandlesClient interface {
	Recv() (*Candle, error)
	grpc.ClientStream
}

type dexterDataStreamCandlesClient struct {
	grpc.ClientStream
}

func (x *dexterDataStreamCandlesClient) Recv() (*Candle, error) {
	m := new(Candle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dexterDataClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/DexterData/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DexterDataServer is the server API for DexterData service.
type DexterDataServer interface {
	SupportedExchanges(context.Context, *ExchangesRequest) (*ExchangesResponse, error)
	SupportedMarkets(context.Context, *MarketsRequest) (*MarketsResponse, error)
	GetCandles(context.Context, *CandlesRequest) (*CandlesResponse, error)
	StreamCandles(*CandlesRequest, DexterData_StreamCandlesServer) error
	Test(context.Context, *TestRequest) (*TestResponse, error)
}

func RegisterDexterDataServer(s *grpc.Server, srv DexterDataServer) {
	s.RegisterService(&_DexterData_serviceDesc, srv)
}

func _DexterData_SupportedExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexterDataServer).SupportedExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DexterData/SupportedExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexterDataServer).SupportedExchanges(ctx, req.(*ExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexterData_SupportedMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexterDataServer).SupportedMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DexterData/SupportedMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexterDataServer).SupportedMarkets(ctx, req.(*MarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexterData_GetCandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexterDataServer).GetCandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DexterData/GetCandles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexterDataServer).GetCandles(ctx, req.(*CandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexterData_StreamCandles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CandlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DexterDataServer).StreamCandles(m, &dexterDataStreamCandlesServer{stream})
}

type DexterData_StreamCandlesServer interface {
	Send(*Candle) error
	grpc.ServerStream
}

type dexterDataStreamCandlesServer struct {
	grpc.ServerStream
}

func (x *dexterDataStreamCandlesServer) Send(m *Candle) error {
	return x.ServerStream.SendMsg(m)
}

func _DexterData_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexterDataServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DexterData/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexterDataServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DexterData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DexterData",
	HandlerType: (*DexterDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupportedExchanges",
			Handler:    _DexterData_SupportedExchanges_Handler,
		},
		{
			MethodName: "SupportedMarkets",
			Handler:    _DexterData_SupportedMarkets_Handler,
		},
		{
			MethodName: "GetCandles",
			Handler:    _DexterData_GetCandles_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _DexterData_Test_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCandles",
			Handler:       _DexterData_StreamCandles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data.proto",
}
